### PR TITLE
SPIKE: Update to 0.7 or another available version

### PR DESCRIPTION
**Pull request by roborourke**
#### Acceptance criteria:

- [ ] investigate more recent changes and decide on a version to update to

Timebox: 0.5 day

### CODE REVIEW

**Comment by owaincuvelier** [comment]
@veselala does this plugin still need to be updated?

**Comment by veselala** [comment]
@roborourke probably have some more insights on that topic?

**Comment by roborourke** [comment]
It does yeah, though it’s not entirely straightforward as we have some modifications in our version.

There’s a recent security update that we need to include, 0.7.2

**Comment by owaincuvelier** [comment]
Okay. @veselala shall I leave this for you to manage in the backlog?

**Comment by veselala** [comment]
yes, will take care

**Comment by veselala** [comment]
@jerico we timeboxed this one to half a day and moved it to the backlog

**Comment by sivanovhm** [comment]
I am uncertain of what has to be done here.

What I got from this ticket is: 
* Change Two-Facto version to 0.7.2
* Test 

Is there any code comparison involved? If yes, this ticket is not appropriate for me to take over.

**Comment by roborourke** [comment]
@sivanovhm this is quite heavy on the software / wordpress knowledge side. This repo is forked from Automattic's original version as we made some modifications a few years ago.

What needs to happen here is to update this plugin from the upstream repo, while maintaining the changes we made. It's possible our updates have made it in to the upstream version though. This all needs to be checked and tested and then a new release created from this repo.

**Comment by mikelittle** [comment]
Having looked at the changes in the upstream plugin. I think we should upgrade to version 0.73. That will include the security fix and some more recent updates including some accessibility fixes.
There is a version 0.8 release planned, but the releases on this plugin tend to be a bit slow, so I wouldn't wait for that.

@veselala Should I mark this as closed for the sprint stats? It is actually the PR, so it could then be re-opened. Or a new ticket created for the actual update.

**Comment by veselala** [comment]
@mikelittle please create a new ticket for the update, as this was marked as a spike.

**Comment by mikelittle** [comment]
New ticket created https://app.zenhub.com/workspaces/vulcan-6284e0dfb386b00c83981426/issues/humanmade/product-dev/1285

**Pull request closed without merging**
